server:
  port: 9527
eureka:
  instance:
    hostname: localhost
  client:
  # 通过register-with-eureka 和 fetch-registry 标识自己是一个服务端
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
