spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nishuonishuoshuo/springCloud/
          searchPaths: tree/master/config-server/src/main/resources/properties
      label: master
          #公开仓库不需要密码
          #  username: xx
          #  password: xx
server:
  port: 1115
