spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nishuonishuoshuo/springCloud/
          searchPaths: respo
server:
  port: 1115
